# Generated by Django 6.0.2 on 2026-02-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_email_alter_student_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
