# Generated by Django 6.0.2 on 2026-02-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
