# Generated by Django 6.0.2 on 2026-02-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_phone_number_alter_student_reg_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(default='student', max_length=50),
        ),
    ]
