# Generated by Django 6.0.2 on 2026-02-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
