# Generated by Django 6.0.2 on 2026-02-13 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_addoncourse_department'),
        ('student', '0006_student_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profil',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
