# Generated by Django 6.0.2 on 2026-02-26 05:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_department_alter_student_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
