# Generated by Django 6.0.2 on 2026-02-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_addoncourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='addoncourse',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.department'),
        ),
    ]
