# Generated by Django 6.0.2 on 2026-02-13 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_addoncourse_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addoncourse',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.department'),
            preserve_default=False,
        ),
    ]
