# Generated by Django 6.0.2 on 2026-02-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addoncourse',
            name='status',
        ),
    ]
