# Generated by Django 6.0.2 on 2026-02-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_remove_addoncourse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addoncourse',
            name='course_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=50),
        ),
    ]
